version: "3.8"
services:
  node:
    container_name: node
    build:
      context: .
    ports:
      - 3000:3000
    environment:
      - MONGO_DB_USERNAME=admin
      - MONGO_DB_PASSWORD=password

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=my_db
    volumes:
      - ./mongo_db_data:/data/db

volumes:
  mongo_db_data:
    driver: local
